### ISSUE TITLE
Symfony 3.3 error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "EightPointsGuzzleBundle" from namespace "EightPoints\Bundle\GuzzleBundle".     when loading into AppKernel

### ISSUE THREAD

**Issue by pc-magas** [8p/EightPointsGuzzleBundle#137]
Over my project I have the following packages into `composer.json` (for some reasons I cannot put it in full):

```json
{
    "name": "pcmagas/super_app",
    "license": "MIT",
    "type": "project",
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "files": [
            "vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php"
        ]
    },
    "require": {
        "php": ">=5.5.9",
        "doctrine/annotations": "*",
        "eightpoints/guzzle-bundle": "^6.1",
        "guzzlehttp/guzzle": "~6.0",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "squizlabs/php_codesniffer": "3.*"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": null
    }
}
```

And over the `AppKernel.php` I have put:

```php
            new EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle()
```

Resulting into this `AppKernel`

```php
<?php

use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
            new EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle()
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();

            if ('dev' === $this->getEnvironment()) {
                $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
                $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
            }
        }

        return $bundles;
    }

    public function getRootDir()
    {
        return __DIR__;
    }

    public function getCacheDir()
    {
        return dirname(__DIR__).'/var/cache/'.$this->getEnvironment();
    }

    public function getLogDir()
    {
        return dirname(__DIR__).'/var/logs';
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');
    }
}
```

Furthermore on `config.yml` I have put:

```yml
eight_points_guzzle:
    clients:
        api_chuck:
            base_url: "%server_url%"
```

But when I try either to run:

```
php ./bin/console server:run
```

Or

```
composer require --dev phpunit/phpunit ^6.4
```

I get the following error:

> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "EightPointsGuzzleBundle" from namespace "EightPoints\Bundle\GuzzleBundle".
Did you forget a "use" statement for another namespace? in /home/pcmagas/Kwdikas/job/enikos_frontend_remake/app/AppKernel.php:18
Stack trace:
#0 /home/pcmagas/Kwdikas/job/enikos_frontend_remake/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /home/pcmagas/Kwdikas/job/enikos_frontend_remake/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/pcmagas/Kwdikas/job/enikos_frontend_remake/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/pcmagas/Kwdikas/job/enikos_frontend_remake/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symf in /home/pcmagas/Kwdikas/job/enikos_frontend_remake/app/AppKernel.php on line 18

Do you think that I am doing something wrong or is actually library's bug?

Also I tried to check if is something I misconfigured by commenting parts of `config.yml`,`AppKernel.php` and `services.yml` and reinstalling the library. Afterwards all the comented parts and still I am getting the error the error. All configurations do seem according to the Readme.md

**Comment by florianpreusner** [comment]
You are using v6.1. I think you followed the README.md from master (default GitHub page). We are preparing release for v7 which contains some renaming changes. Please follow README.md that is part of the downloaded vendor lib. There you should see that you have to add following class: new EightPoints\Bundle\GuzzleBundle\GuzzleBundle()

https://github.com/8p/EightPointsGuzzleBundle/blob/v6.1.0/README.md

**Comment by pc-magas** [comment]
I think there should be a refrence on Readme.md that is located to master branch in order to help people that have similar prob.

**Comment by florianpreusner** [comment]
Hey @pc-magas, thanks for your input. Can you provide more details? How would you solve this issue exactly? I think it's hard to solve cause it can always happen that someone is using an older version that master...

**Comment by pc-magas** [comment]
Just put on master's Readme.md the following content:

> For users that use Symfony 3.3 or later please read [this](https://github.com/8p/EightPointsGuzzleBundle/blob/v6.1.1/README.md) Information

So each one that looks on README.md will get pointed to the correct documentation/instructions.
