### ISSUE TITLE
Not implementing reset() from DataCollectorInterface is deprecated in Symfony 3.4

### ISSUE THREAD

**Issue by ThomasTr** [8p/EightPointsGuzzleBundle#141]
I'm upgrading a Symfony app to 3.4 and I found this deprecation related to your HttpDataCollector:

User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "EightPoints\Bundle\GuzzleBundle\DataCollector\HttpDataCollector".

**Comment by gregurco** [comment]
@ThomasTr thank you for reporting :+1: I created PR with fix: #142

**Comment by florianpreusner** [comment]
Released in v7.1.0 (https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v7.1.0)

**Comment by florianpreusner** [comment]
Released also in v6.1.2 (https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v6.1.2)

**Comment by ThomasTr** [comment]
Thank you @gregurco @florianpreusner
