### ISSUE TITLE
README.md Usage error

### ISSUE THREAD

**Issue by lcp0578** [8p/EightPointsGuzzleBundle#144]
It should be

 ` new EightPoints\Bundle\GuzzleBundle\GuzzleBundle()`

not 
`new EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle()`

thanks

**Comment by lcp0578** [comment]
Configuration in config.yml:

`eight_points_guzzle:`  => `guzzle:`

**Comment by gregurco** [comment]
@lcp0578 but why? We renamed bundle class name and configuration key in version 7.0. You can see in here: https://github.com/8p/EightPointsGuzzleBundle/blob/v7.0.0/README.md

**Comment by lcp0578** [comment]
oh,but i used `composer require eightpoints/guzzle-bundle` is it v4.5.3, but to a newcomer like me, it  is so confusing. 
maybe, it make a note for different versions.

**Comment by gregurco** [comment]
@lcp0578 so, if you install v4.5.3 then you have to read proper readme: https://github.com/8p/EightPointsGuzzleBundle/blob/v4.5.3/README.md

But my suggestion is to upgrade to latest stable version. There are new features, improvements, bug fixes and tests.

**Comment by lcp0578** [comment]
Thanks, i will upgrade it.
