### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by matteomoretti** [8p/EightPointsGuzzleBundle#145]
Hi,

first of all, thanks for this bundle! 

I can't find a changelog: where is it? I would know what's changed from 6.* to 7.*, without digging the entire codebase. 

Thanks a lot

**Comment by gregurco** [comment]
@matteomoretti hello. Probably here you can find changelog: https://github.com/8p/EightPointsGuzzleBundle/releases
Is it what you want?

**Comment by matteomoretti** [comment]
@gregurco yes, thanks a lot! :)
