### ISSUE TITLE
Migrating from 6.x to 7.x. Where is UPDATE.md?

### ISSUE THREAD

**Issue by DonCallisto** [8p/EightPointsGuzzleBundle#149]
Hello guys.
I would like to keep my dependencies as updated as possible but with your bundle I cannot be sure that the update would not break all the things.
Could you please include an `UPDATE.md` file to guide everyone in this operation?

Thank you in advance.

**Comment by DonCallisto** [comment]
Looking at [7.0 release](https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v7.0.0) it seems that only configuration files are involved in this process. Can you confirm?

**Comment by gregurco** [comment]
@DonCallisto 
1) if you used wsse middleware then you should install and activate https://github.com/gregurco/GuzzleBundleWssePlugin
2) if you used "headers" config outside of "options" config then you should move them

**Comment by DonCallisto** [comment]
@gregurco I think also configuration file keys (e.g.: `guzzle` is now `eight_points_guzzle`) and namespaces should be changed.

**Comment by gregurco** [comment]
@DonCallisto yep, you are right

**Comment by DonCallisto** [comment]
So, apart from wsse plugin:

- Register the bundle under new name
- change config keys from `guzzle` to `eight_points_guzzle`
- move `headers` key under `options` config

No other actions needed: your switch from `PSR-0` to `PSR-4` keeping same namespace prefix and mapping `PSR-4` to `src` base directory (with all file moved under `src`) has granted a sort of "backward compatibility" in class loading. Awesome!

**Comment by gregurco** [comment]
@DonCallisto please take a look at https://github.com/gregurco/EightPointsGuzzleBundle/blob/9c20a31760ecf137ecc667203cfc5bf4d8c72a3e/UPGRADE.md Do you have something to add?

**Comment by DonCallisto** [comment]
@gregurco yes, if you have created any services, you should change name aswell like

before

`<argument type="service" id="guzzle.client.xyz" />`

after

`<argument type="service" id="eight_points_guzzle.client.xyz" />`

**Comment by gregurco** [comment]
@DonCallisto thanks you, I added: https://github.com/gregurco/EightPointsGuzzleBundle/blob/51e45461e40635db3ff525a39ec2ec7422bb07b3/UPGRADE.md

Other remarks?

**Comment by DonCallisto** [comment]
I think that's all!

**Comment by gregurco** [comment]
@DonCallisto thanks you. I think tomorrow it will be merged.

**Comment by DonCallisto** [comment]
Thanks!
It will be very useful!

**Comment by florianpreusner** [comment]
Released in v7.2.0 (https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v7.2.0)

**Comment by DonCallisto** [comment]
Thank you guys
