### ISSUE TITLE
[PENDING] Implement PSR-15

### ISSUE THREAD

**Issue by gregurco** [8p/EightPointsGuzzleBundle#169]
For now, PSR-15 is draft, but when it will be released, all middlewares should be compatible and implement MiddlewareInterface.

Link to draft: https://github.com/php-fig/fig-standards/blob/hotfix/psr-15-interface-syntax/proposed/http-handlers/request-handlers.md
Link to official site: http://www.php-fig.org/psr/
Related issue in guzzle: https://github.com/guzzle/guzzle/issues/1702

**Comment by jeremeamia** [comment]
[PSR-15](https://www.php-fig.org/psr/psr-15/) was created for _server_ middleware, not client middleware. If you look at the `MiddlewareInterface`, the contract is designed for the `ServerRequestInterface`, so I don't think PSR-15 would apply to Guzzle clients.

**Comment by gregurco** [comment]
@jeremeamia thank you for information :+1:
