### ISSUE TITLE
Profiler shows only the first call

### ISSUE THREAD

**Issue by sparrowek** [8p/EightPointsGuzzleBundle#171]
| Q                | A
| ---------------- | -----
| Symfony version  | 3.4.1
| Bundle version   | 7.2.1

Only the first call is shown with request and response textareas.
For successive calls only its url is presented. The url seems to be clickable but clicking does nothing.

**Comment by gregurco** [comment]
@sparrowek please try to execute `bin/console assets:install`

**Comment by sparrowek** [comment]
Thanks, it worked. 
I just wonder why this step was not fired when I have required the module in composer?

**Comment by gregurco** [comment]
Probably it's something related to last changes in symfony 3.4. I will investigate this problem later. Thank you for reporting :+1:
