### ISSUE TITLE
Improve assets for compatibility with symfony 3.4/4.0

### ISSUE THREAD

**Issue by gregurco** [8p/EightPointsGuzzleBundle#172]
Assets are not installed automatically in symfony 3.4/4.0.

 - [x] add `symfony/framework-bundle` in requirements (there is defined `assets:install` command and `symfony/asset` package in dependencies)
 - [ ] add `assets:install` command in recipe (source: https://github.com/symfony/recipes#composer-scripts-configurator)

**Comment by florianpreusner** [comment]
Part 1 released in v7.3.0 (https://github.com/8p/EightPointsGuzzleBundle/releases/tag/7.3.0)

**Comment by florianpreusner** [comment]
Part 2 is not necessary cause assets:install will be run by framework-bundle.
https://github.com/symfony/recipes-contrib/pull/512#discussion_r221609209

Thanks for the hint, @gregurco! 🙌
