### ISSUE TITLE
How to activate/connect plugins with the new symfony 3.4/4.0 bundles system?

### ISSUE THREAD

**Issue by ericlery** [8p/EightPointsGuzzleBundle#182]
| Q                | A
| ---------------- | -----
| Symfony version  | 3.4.0
| Bundle version   | 7.3.0

**Comment by gregurco** [comment]
@ericlery for 3.4 it's the same flow, because there still exists AppKernel class with bundles listed, but with 4.0 we should find solution. Thanks for reporting.

**Comment by ericlery** [comment]
@gregurco in fact you can use the 4.0 way with 3.4 as 3.4 is 4.0 with deprecations. So it affect 3.4 and 4.0

**Comment by gregurco** [comment]
Fixed in #197 
Thank you for reporting the problem :+1:
