### ISSUE TITLE
Profiler first Responsetextarea is empty

### ISSUE THREAD

**Issue by dariotilgner** [8p/EightPointsGuzzleBundle#188]
| Q                | A
| ---------------- | -----
| Symfony version  | 4.0.6
| Bundle version   | 7.3.0
| php version | 7.2.2

I just have installed your Bundle. On any site which fires a guzzle request the first (also if it is the only) response in the textarea isn't shown. 
![eightpointsguzzlebundleerror](https://user-images.githubusercontent.com/1674931/37449743-c83436c6-282b-11e8-9220-0eb00cf9a8ac.PNG)
I also reinstalled the assets and deleted the cache. 

After debugging in my vendor files (shame on me) the error seems to occure from lines 98 and 101 in https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/views/profiler.html.twig

If I change the `.val(..)` method call to `.text(..)` this fixes my problem. Then all textareas are getting filled

**Comment by gregurco** [comment]
@dariotilgner hello! Thank you for reporting an issue. Today I will try to check.

**Comment by dariotilgner** [comment]
@gregurco I just got the information from annother project in my company that this problem also occures sometimes**(!)** in symfony version 3.3.0

**Comment by dariotilgner** [comment]
@gregurco The fix works fine! :)

**Comment by gregurco** [comment]
@dariotilgner thank you for testing :) gonna merge it in few days. Track #189

**Comment by gregurco** [comment]
@dariotilgner close this issue. PR #189 was merged. Thanks you once again :+1:
