### ISSUE TITLE
token storage

### ISSUE THREAD

**Issue by vladislavs1321** [8p/EightPointsGuzzleBundle#190]
| Q                | A
| ---------------- | -----
| Symfony version  | 3.4| 4+
| Bundle version   | 1.0.3

is it possible to have default toke storage/cache to prevent each api call producing new token?

**Comment by gregurco** [comment]
@vladislavs1321 is this issue related to https://github.com/gregurco/GuzzleBundleOAuth2Plugin ?

**Comment by vladislavs1321** [comment]
oh, sorry.
