### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by vladislavs1321** [8p/EightPointsGuzzleBundle#194]
| Q                | A
| ---------------- | -----
| Symfony version  | 3.4
| Bundle version   | 7.3.0

@gregurco
Hello , Is it possible to register custom Middleware per client with configuration?

**Comment by gregurco** [comment]
Do you know about events https://github.com/8p/EightPointsGuzzleBundle#events ? You can define pre-request / post-request. Is it  what you need or do you need exactly middleware?

**Comment by gregurco** [comment]
@vladislavs1321 did it resolve your problem or do you need another functionality?

**Comment by vladislavs1321** [comment]
@gregurco  for this moment i've handled everything with events, thanks. Solved.
