### ISSUE TITLE
Erro UnexpectedValueException in Profiler

### ISSUE THREAD

**Issue by tiagofranco86** [8p/EightPointsGuzzleBundle#199]
Hello, I'm working with a project for development with synfony 3.4 in php 5.6. Because of the PHP version, I had to install version 6.2. Services configured and working properly, but errors are occurring in profiler rendering with "The profiler template" GuzzleBundle :: debug.html.twig "for data collector" guzzle "does not exist."
I noticed that the synfony 3.0 syntax change is due to how templates are extended / included.

{% extends "WebProfilerBundle:Profiler:layout.html.twig" %}
however, since Symfony 3.4 we should use:
{% extends "@WebProfiler/Profiler/layout.html.twig" %}

Is there any way around this without having to change my library sources in the vendor?

| Symfony version  | 3.4
| Bundle version     | ^6.2
| PHP                     |5.6

**Comment by gregurco** [comment]
@tiagofranco86 hello! Thank you for reporting. I will investigate this issue today later and I guess there is solution :slightly_smiling_face:

**Comment by tiagofranco86** [comment]
Ops correcting
I noticed that the synfony 3.0 syntax change is due to how templates are extended / included.

{% extends "WebProfilerBundle:Profiler:layout.html.twig" %}
however, since Symfony 3.4 we should use:
{% extends "@WebProfiler/Profiler/layout.html.twig" %}

**Comment by gregurco** [comment]
@tiagofranco86 are you sure you are using Symfony 3.4 with PHP 5.6? I see that SF 3.4 is requiring PHP 7: https://github.com/symfony/website-skeleton/blob/v3.4.0/composer.json#L7

**Comment by gregurco** [comment]
Fixed in PR #200 and released in https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v6.2.1

**Comment by tiagofranco86** [comment]
Hello @gregurco 
Sorry for the delay of the feedback, issue solved. Thank you!
