### ISSUE TITLE
Profiler PATCH method invisible

### ISSUE THREAD

**Issue by gregoirepaqueron** [8p/EightPointsGuzzleBundle#201]
| Symfony version  | 3.4.11
| Bundle version   | 7.3.0

Hello,

When guzzle does request, and the response have code 204, the display on the profiler has no background color + code written in blank color.

**Comment by gregurco** [comment]
@gregoirepaqueron thanks for reporting, I will try to test it ASAP :+1:

**Comment by gregurco** [comment]
@gregoirepaqueron I tested with same version of symfony and bundle and it seems to be ok. Could you please check my screenshot and provide yours if it's not the same?

![selection_001](https://user-images.githubusercontent.com/4052904/41146225-5775a3a2-6b0b-11e8-8d31-3a3c50eb4b19.png)

**Comment by gregoirepaqueron** [comment]
@gregurco Here's my screenshot : 
![screencapture-basemandat-local-8080-_profiler-802365-2018-06-08-11_05_27](https://user-images.githubusercontent.com/2579201/41149782-bdb1bd26-6b0c-11e8-9799-9d608c97287a.png)

As you can see, i have 3 calls code 204. with no background color + "No content (204) written in blank color, i have to highligh it to be seen.
Then i have 1 call with 500, and 1 call with 400 (it looks like there is encoding problem on the french name btw).

I will look further to see if some CSS are problematics.

**Comment by gregoirepaqueron** [comment]
Oh, i think the problem is the PATCH method, not the code 204 :)

**Comment by gregurco** [comment]
@gregoirepaqueron yep, got it :) I think today/tomorrow I will fix it. Thanks :slightly_smiling_face:

**Comment by gregoirepaqueron** [comment]
Thanks :)

**Comment by gregurco** [comment]
@gregoirepaqueron fixed in #203 . Thanks for reporting :slightly_smiling_face:

**Comment by gregoirepaqueron** [comment]
:+1:
