### ISSUE TITLE
[Profiler] General Improvements

### ISSUE THREAD

**Issue by gregurco** [8p/EightPointsGuzzleBundle#210]
Todo:
- [x] Collapsible **Request** and **Response** section _(sometimes there are a lot of data in request/response section and user might want to collapse it)_
=> https://github.com/8p/EightPointsGuzzleBundle/issues/222
- [x] Total requests time on the profiler page _(not only in bottom bar)_. It can be useful in the API projects, because there bottom bar is not used.
=> https://github.com/8p/EightPointsGuzzleBundle/issues/223
- [x] More detailed request time description: dns lookup time, connection time, etc..
=> https://github.com/8p/EightPointsGuzzleBundle/issues/224
- [x] In left menu counter of request can be red if there are failed requests (response status >= 400)
=> https://github.com/8p/EightPointsGuzzleBundle/issues/225
- [x] If request time is more than expected (should be configurable) then time label should change the color.
=> https://github.com/8p/EightPointsGuzzleBundle/issues/226

**Comment by florianpreusner** [comment]
We should split each topic into separate issues later, before starting. Should only be a list of upcoming improvements in general. What you think @gregurco?

**Comment by gregurco** [comment]
@florianpreusner yep, agree with you :+1:

**Comment by florianpreusner** [comment]
Extracted all topics into separated tickets. Ticket will be closed.
