### ISSUE TITLE
[Symfony Flex] Add more useful params in recipe

### ISSUE THREAD

**Issue by florianpreusner** [8p/EightPointsGuzzleBundle#218]
Right now only [3 params are given as example in Symfony Flex recipe](https://github.com/symfony/recipes-contrib/blob/master/eightpoints/guzzle-bundle/7.0/config/packages/eight_points_guzzle.yaml). There are more useful params that should be provided.

Full list: https://github.com/gregurco/EightPointsGuzzleBundle/blob/configuration_reference/src/Resources/doc/configuration-reference.md

Suggestion:
- adding link to full list of params
- logging
- guzzle-bundle-oauth2-plugin (deactivated) with link to more plugins

Added by comments:
- http_errors

**Comment by florianpreusner** [comment]
@gregurco What do you think?

**Comment by florianpreusner** [comment]
Created PR: https://github.com/symfony/recipes-contrib/pull/519

**Comment by florianpreusner** [comment]
Going to remove "[WIP]" from PR title once you checked, @gregurco.

**Comment by gregurco** [comment]
@florianpreusner Looks good to me :+1: Approved PR.

**Comment by florianpreusner** [comment]
Merged: https://github.com/symfony/recipes-contrib/pull/519
Ticket will be closed.
