### ISSUE TITLE
Client autowiring

### ISSUE THREAD

**Issue by rrajkomar** [8p/EightPointsGuzzleBundle#227]
Since autowiring is obviously a big thing that will most likely stay :)
maybe now would be a good time to start thinking about whether it'd be possible to move away from the current client configuration to something more autowiry-like.

What's your take on this subject ?

**Comment by gregurco** [comment]
Yep, but `autorwire` is more related to one-class services. In out case we can have 5 clients and all 5 clients will be instance of the same class and in this case it's impossible to autowire without some additional configuration. Also we have an article where we described how to use autowire in context of this bundle: https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/autowiring-clients.md

**Comment by gregurco** [comment]
@rrajkomar did the article answer your question? Can we close the issue or do you have any suggestions?

**Comment by rrajkomar** [comment]
Sorry.
Well from youranswer I guess the only way to move away from the current way would be making the Client class abstract and therefore induce a bc break.
We might talk about this again later on but it can be closed for now.
