### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by rpkamp** [8p/EightPointsGuzzleBundle#231]
Master is quite a bit ahead of the latest release. Could you cut a new tag please?

https://github.com/8p/EightPointsGuzzleBundle/compare/v7.3.1...master

**Comment by florianpreusner** [comment]
Already planned: https://github.com/8p/EightPointsGuzzleBundle/milestone/6

**Comment by gregurco** [comment]
@rpkamp https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v7.4.0 - published
