### ISSUE TITLE
symfony/stopwatch rqeuired

### ISSUE THREAD

**Issue by HEKET313** [8p/EightPointsGuzzleBundle#238]
| Symfony version  | 4.1.6
| Bundle version   | 7.4.0

I executed `composer update`, your bundle updated and I've got an error "Eightpoint GuzzleBundle profiling requires "symfony/stopwatch" package" on "cache clear" stage. I see that your package requires this package under dev environment, but why it requires this package after including into project?

![image](https://user-images.githubusercontent.com/4463911/47648505-4935cd80-db8b-11e8-8cc4-7bc063008a49.png)

**Comment by gregurco** [comment]
Hello.
Do you run `composer update` in prod environment? Bundle requires `symfony/stopwatch` package in dev only and normally it should be installed in dev.

**Comment by HEKET313** [comment]
Nope, I don't run `composer update` in prod, but packages don't install their's dev requirements even under dev environment.

**Comment by HEKET313** [comment]
I won't argue, but I don't agree. Anyway, thank you for your time and fast response

**Comment by gregurco** [comment]
I agree with you too. I will try to find more elegant solution :slightly_smiling_face: Thank you for reporting.

**Comment by gregurco** [comment]
@HEKET313 fixed in PR #239. Thank you for reporting this issue :slightly_smiling_face:
