### ISSUE TITLE
Question: Does your bundle support JWT?

### ISSUE THREAD

**Issue by murman-lexus** [8p/EightPointsGuzzleBundle#251]
Hi Guys! Nice Bundle! 

how Can I Use JWT Authorization?

I need  install plugin 
or use guzzle_bundle.pre_transaction event(https://github.com/8p/EightPointsGuzzleBundle/issues/38)
or Something else? 

Thanks in advance

**Comment by gregurco** [comment]
Hello @murman-lexus 
This bundle fully supports functionality of guzzle. So in this case you can use pre transaction event with custom logic (jwt handling) or to connect already created 3rd party middleware: https://github.com/eljam/guzzle-jwt-middleware
You can connect through plugins system how it's described here: https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/how-to-create-a-single-file-plugin.md
