### ISSUE TITLE
Oauth header not logged due to handler stack order

### ISSUE THREAD

**Issue by andreicio** [8p/EightPointsGuzzleBundle#253]
| Q                | A
| ---------------- | -----
| Symfony version  | 4.2.7
| Bundle version   | 7.5.0

In \EightPoints\Bundle\GuzzleBundle\DependencyInjection\EightPointsGuzzleExtension::createHandler the plugins are added last to the handler stack, after the logging middleware. This means that the OAuth header does not show in the eight_points_guzzle panel of the profiler.
Is there any reason for this order? I tried moving the plugins above the logging and it seems to work fine.

**Comment by gregurco** [comment]
Hello @andreicio
I guess there are no reason to do like that, but I will recheck it and fix it to provide better logging :+1:

**Comment by gregurco** [comment]
Fixed in PR #270
