### ISSUE TITLE
Output cUrl command

### ISSUE THREAD

**Issue by bigfoot90** [8p/EightPointsGuzzleBundle#266]
For debugging purposes it would be nice to have a way to replicate the request out of php.
I'll make a PR in the next days.

**Comment by bigfoot90** [comment]
Sorry wong repo

**Comment by bigfoot90** [comment]
What you need to merge #267 ?

**Comment by gregurco** [comment]
@bigfoot90 the PR is ok. First of all I want to check some minor issue and probably to do one more fix for version 7. After that we will start preparing for v8 and your task will be merged to master, that will become v8. Are you ok, if we will merege it in few days?

**Comment by bigfoot90** [comment]
This is not a BC, so it can be merged on v7 as minor version. Please let me know what can I do to speed up this and close this work. Thanks.

**Comment by gregurco** [comment]
@bigfoot90 it's not about BC. It's more about new release we plenned to do some time ago and to motivate developers to migrate to new version via new features.
Do you need this change ASAP in release or you can use master or wait for new release? It's important for us, because you did the PR.

**Comment by bigfoot90** [comment]
It's OK. It is not ASAP, I only need to close this work on my side.

**Comment by gregurco** [comment]
@bigfoot90, I think it's totally done on your side. You will receive emeil, when PR will be merged.
Thank you!
