### ISSUE TITLE
Deprecation in EventDispatcher

### ISSUE THREAD

**Issue by cigraphics** [8p/EightPointsGuzzleBundle#268]
User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.

The issue relies in Middleware/EventDispatchMiddleware.php

There are 3 usages of 

$this->eventDispatcher->dispatch(GuzzleEvents::PRE_TRANSACTION, $preTransactionEvent);
$this->eventDispatcher->dispatch(GuzzleEvents::POST_TRANSACTION, $postTransactionEvent);

Cheers

**Comment by gregurco** [comment]
Hello @cigraphics 
Thank you for reporting. This deprecation message was fixed in PR #265 . This changes will be released next days. You have two options: move to `dev-master` version or wait few days for new release. Also you can sudscribe for new releases by "watch" button at the top of the page.
