### ISSUE TITLE
Upgrade PHPUnit from 6 to 7

### ISSUE THREAD

**Issue by gregurco** [8p/EightPointsGuzzleBundle#275]
Version 6 of PHPUnit is already not supported. We have to migrate to version 7. Version 8 is not proper for us yet, because it required at least PHP 7.2.

More info: https://phpunit.de/supported-versions.html
Useful link: https://github.com/8p/EightPointsGuzzleBundle/blob/master/phpunit.xml.dist#L9

**Comment by espipj** [comment]
I suggest you to use https://github.com/rectorphp/rector to do so ;)

**Comment by RageZBla** [comment]
Let me try to take a stab at this one, I want to play with rector as well.

**Comment by RageZBla** [comment]
@gregurco is it OK to remove support for PHP 7.0 on travis?

**Comment by gregurco** [comment]
@RageZBla the support of PHP 7.0 is dropped in #274. So your PR will be merged after it.
