### ISSUE TITLE
Symfony 4.4 profiler stops working on latest 8.0.0 release

### ISSUE THREAD

**Issue by jmatthiesen81** [8p/EightPointsGuzzleBundle#292]
| Q                | A
| ---------------- | -----
| Symfony version  | 4.4.2
| Bundle version   | v8.0.0
| PHP Version | 7.4.0

The Symfony profiler stops working throwing the following error:
Unexpected error occured: Neither the property "iconColor" nor one of the methods "iconColor()", "geticonColor()"/"isiconColor()"/"hasiconColor()" or "__call()" exist and have public access in class "EightPoints\Bundle\GuzzleBundle\DataCollector\HttpDataCollector".

This changeset seems to be the reason:
https://github.com/8p/EightPointsGuzzleBundle/compare/v7...master#diff-dbe279674682f3b82012c7034e9fdd65L202

**Comment by gregurco** [comment]
Hello @jmatthiesen81 
Thank you for reporting the issue. Could you please clear the cache and check if the issue will appear? We totally removed `iconColor` and you can check that there is no mention of `iconColor` in the code at all.

Which cache can cause the problem: symfony cache or opcache

Thanks.

**Comment by jmatthiesen81** [comment]
I thought, that the automatically executed clear cache command from composer at the end of an update process is enough. After manually clearing the cache it worked. Trying to reproduce the problem by downgrading to 7.6 and updating back to 8.0 is currently not possible. Did you revoked the package from packagist?

**Comment by gregurco** [comment]
Thanks for checking.
I did a release by mistake :slightly_frowning_face: I want to check one reported bug before release. For now you can use dev-master and it will be released next days.
