### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by rvanlaak** [8p/EightPointsGuzzleBundle#295]
| Q                | A
| ---------------- | -----
| Symfony version  | 5.0.3
| Bundle version   | 8.0.0

The following two css rules cause problems for dark mode:

![image](https://user-images.githubusercontent.com/2707563/73276562-30322700-41e9-11ea-9280-d6f3d030b506.png)

![image](https://user-images.githubusercontent.com/2707563/73276587-39bb8f00-41e9-11ea-9464-0b0ec513312d.png)

## Before

![image](https://user-images.githubusercontent.com/2707563/73276526-1e508400-41e9-11ea-84a5-aa6846cf1b7e.png)

## After removing CSS rules

What about removing the two lines?

![image](https://user-images.githubusercontent.com/2707563/73276629-48a24180-41e9-11ea-9f7e-c95f9838d601.png)

**Comment by gregurco** [comment]
Hello
Good observation! I'm not sure about removing, because we want to highlight these boxes, but I think dark mode adds some classes at the top level. I think we can add some rules, when dark mode is activated, colors will switch to dark style or light style, but not the same as background.

**Comment by rvanlaak** [comment]
Would be good to follow the Symfony best practices on styling of the panels. Might be an idea to reuse the css classes from the profiler?

**Comment by gregurco** [comment]
> reuse the css classes
which classes do you mean? Could you give examples?

**Comment by rvanlaak** [comment]
These can be found at [`symfony/web-profiler-bundle/Resources/views/Profiler/profiler.css.twig`](https://github.com/symfony/web-profiler-bundle/blob/master/Resources/views/Profiler/profiler.css.twig), which is the base CSS that gets imported when the pane would [`@WebProfiler/Profiler/base.html.twig`](https://github.com/symfony/web-profiler-bundle/blob/master/Resources/views/Profiler/base.html.twig).

As example I'd advise using:

* .metric
* .badge
* .sf-tabs (also have js behavior)

**Comment by gregurco** [comment]
@rvanlaak sorry for the late reply. I think the idea is good, to use classes provided by symfony.
Do you want to integrate that? PR is welcome.

**Comment by gregurco** [comment]
Done in #316
