### ISSUE TITLE
There are no registered paths for namespace "EightPointsGuzzleBundle" 

### ISSUE THREAD

**Issue by goetas** [8p/EightPointsGuzzleBundle#299]
| Q                | A
| ---------------- | -----
| Symfony version  | 4.4.2
| Bundle version   | master
Getting:

`There are no registered paths for namespace "EightPointsGuzzleBundle" in @EightPointsGuzzle/debug.html.twig at line 74.`

**Comment by goetas** [comment]
This is displayed as soon as I try to open the profiler on the guzzle section

**Comment by gregurco** [comment]
@goetas thanks for reporting. Now it's fixed.

**Comment by goetas** [comment]
thanks!
