### ISSUE TITLE
User Deprecated: Since symfony/routing 5.1: The "Symfony\Component\Routing\RouteCollectionBuilder" class is deprecated, use "Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator" instead

### ISSUE THREAD

**Issue by Axent96** [8p/EightPointsGuzzleBundle#310]
| Q                | A
| ---------------- | -----
| Symfony version  | 5.1.3
| Bundle version   | 8.0.1

**Comment by rpkamp** [comment]
I don't think this message is related to EightPointsGuzzleBundle, as it doesn't use the `RouteCollectionBuilder` at all. There is probably another reason in your application why you're getting this deprecation.

**Comment by Axent96** [comment]
I cannot found the application for this problem. So, you are right :) Sorry for my mistake
