### ISSUE TITLE
Can't set cookies to a file path in config

### ISSUE THREAD

**Issue by olivier1980** [8p/EightPointsGuzzleBundle#317]
| Q                | A
| ---------------- | -----
| Symfony version  |v6.0.7
| Bundle version   |v8.3.0  

Guzzle version 7.4.2.

According to the docs, I should be able to enter a string for the 'cookies' value..see https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/configuration-reference.md.

The configuration is locked to a boolean value though, so it won't work. When manually changing the DependencyInject to allow for a string value, I get another error: 'cookies must be an instance of GuzzleHttp\Cookie\CookieJarInterface'.

**Comment by gregurco** [comment]
Hello @olivier1980 
Yes, there is an issue on the configuration reference page. At the client configuration level, the cookie parameter should have a boolean value. Please read here how guzzle cookies work: https://docs.guzzlephp.org/en/stable/quickstart.html#cookies
