### ISSUE TITLE
A log channel by client

### ISSUE THREAD

**Issue by adpeyre** [8p/EightPointsGuzzleBundle#318]
Hi,

Today, all logs of clients are logged in the same channel. \
Is there a solution for a specific client to use a defined channel ?

I would like for example attach an email alert for a specific API (client).

Ty

**Comment by gregurco** [comment]
Hello @adpeyre 

Sorry for the late reply. Special middleware is responsible for logs. You can find this middleware [here](https://github.com/8p/EightPointsGuzzleBundle/blob/v8.3.0/src/Middleware/SymfonyLogMiddleware.php). This middle is defined defined in configuration [here](https://github.com/8p/EightPointsGuzzleBundle/blob/v8.3.0/src/DependencyInjection/EightPointsGuzzleExtension.php#L382). So, you can see that we use special channel: `eight_points_guzzle`. If this channel doesn't help you, as quick solution I can suggest to defined manually another middleware using same middleware class and your own adjusted configuration.
