### ISSUE TITLE
Composer description is outdated

### ISSUE THREAD

**Issue by garak** [8p/EightPointsGuzzleBundle#319]
| Q                | A
| ---------------- | -----
| Symfony version  | irrelevant
| Bundle version   | latest

I was looking for a guzzle bundle, and I was about to discard this one because of its description:

>Integrates Guzzle 6.x, a PHP HTTP Client, into Symfony 2/3/4. Comes with easy and powerful configuration options and optional plugins

It's pretty outdated, maybe it should remove "2/3/4" and mention "Symfony" alone.

**Comment by gregurco** [comment]
Hello 🙂 Thank you for remark. Initially it was a good idea to keep compatibility while developers are migrating projects. Now I agree that it's possible to cut these versions from support. Gonna do it next weeks.
