### ISSUE TITLE
Security dependant bots alert in guzzlehttp/guzzle 

### ISSUE THREAD

**Issue by palanisamy-emis** [8p/EightPointsGuzzleBundle#325]
| Q                | A
| ---------------- | -----
| Symfony version  | 5.4
| Bundle version   | 8.3.0

We have used EightPointsGuzzleBundle package as latest version 8.3.0. In dependencies list guzzlehttp/guzzle package is outdated now and the latest version is 7.5.0 but it is still sticked to version 7.4.2. Could anyone please look into this. Thanks

CC: @gregurco

**Comment by gregurco** [comment]
Hello @palanisamy-emis 
As you can see here: https://github.com/8p/EightPointsGuzzleBundle/blob/master/composer.json#L30 guzzle bundle doesn't force you to use exactly version 7.4.2 of guzzle. You are free to run `composer update guzzlehttp/guzzle` and get fresh version of guzzle.
