### ISSUE TITLE
Error since the support of guzzlehttp/promises v2

### ISSUE THREAD

**Issue by aless673** [8p/EightPointsGuzzleBundle#327]
| Q                | A
| ---------------- | -----
| Symfony version  | 6.2.10
| Bundle version   | 8.3.0

latest release of guzzlehttp/guzzle include this commit : https://github.com/guzzle/guzzle/commit/7936fe9e180ce969680b21c40b221b3c2c661369

so after updating composer vendors, we now have this error `Attempted to call function "rejection_for" from namespace "GuzzleHttp\Promise"`

**Comment by GrahamCampbell** [comment]
https://github.com/8p/EightPointsGuzzleBundle/pull/328 should fix your issue.

**Comment by petski** [comment]
Great work all!

When can we expect a release containing  this fix?

**Comment by gregurco** [comment]
@petski released: https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v8.4.0
