### ISSUE TITLE
Symfony 7.1 - deprecation in Symfony\Component\HttpKernel\DependencyInjection\Extension

### ISSUE THREAD

**Issue by dmamchyts** [8p/EightPointsGuzzleBundle#340]
| Q                | A
| ---------------- | -----
| Symfony version  | 7.1.0
| Bundle version   | 8.5.0

The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "EightPoints\Bundle\GuzzleBundle\DependencyInjection\EightPointsGuzzleExtension".

![image](https://github.com/8p/EightPointsGuzzleBundle/assets/102530135/6e178d1a-961f-49e5-829d-404cd7ff61e9)

**Comment by gregurco** [comment]
@dmamchyts thanks for reporting! Fixed here: https://github.com/8p/EightPointsGuzzleBundle/pull/341

**Comment by dmamchyts** [comment]
@gregurco  do you have any ETA about the new release?

**Comment by gregurco** [comment]
@dmamchyts released: https://github.com/8p/EightPointsGuzzleBundle/releases/tag/v8.5.1
