### ISSUE TITLE
Documentation for HandlerStack

### ISSUE THREAD

**Issue by ppounder** [8p/EightPointsGuzzleBundle#51]
Is there any possibility in updating the documentation to advise how to add Handlers. I can see the functionality has been added via https://github.com/8p/GuzzleBundle/issues/21 but I am not understanding how we can integrate this in.

I am trying to use the GuzzleHttp\Subscriber\Oauth\Oauth1 middleware which can be added onto the HandlerStack, not sure how to do this via this bundle.

Hope you can help

Paul

**Comment by stianmartinsen** [comment]
I would also love some documentation here. I want to use [guzzle-cache-middleware](https://github.com/Kevinrob/guzzle-cache-middleware), but I don't know how to add it using your bundle.

**Comment by gregurco** [comment]
@ppounder we introduces new plugin system and you can add new handlers through plugin. See examples here:
- https://github.com/8p/EightPointsGuzzleBundle/issues/90#issuecomment-338002511
- https://github.com/gregurco/GuzzleBundleWSSEPlugin
- https://github.com/gregurco/GuzzleBundleCachePlugin

@stianmartinsen I created new plugin: https://github.com/gregurco/GuzzleBundleCachePlugin - it implements https://github.com/Kevinrob/guzzle-cache-middleware in GuzzleBundle
