### ISSUE TITLE
Deactivate logging/profiler/data collector completely

### ISSUE THREAD

**Issue by florianpreusner** [8p/EightPointsGuzzleBundle#72]
When setting the option "logging" to false no logging class should be created. Also the data collector (used for profiler) is not necessary than.

**Comment by gregurco** [comment]
Could you please provide more details and I will try to implement it :) I see, that now if logging is false, then DevNullLogger will be created with service id **eight_points_guzzle.logger**. Do you want to not define this service at all in this case or what?

**Comment by florianpreusner** [comment]
Well, not that easy to remember. Unfortunately I didn't provide more info 🤦‍♂️ . I will take a deeper look into this issue the next couple days.

**Comment by gregurco** [comment]
I read this issue one more time and probably I understood what did you mead :smile: In 1-2 days I will do PR and you will review the result.

**Comment by florianpreusner** [comment]
I'm curious 😄

**Comment by florianpreusner** [comment]
Yeah, that seems to be the solution for the problem I have mentioned :) Nice!
